ember: &defaults
  image: danlynn/ember-cli:2.10.0
  volumes:
      - .:/myapp

npm:
  <<: *defaults
  command: npm

bower:
  <<: *defaults
  command: bower --allow-root


server:
  <<: *defaults
  command: server --watcher polling
  ports:
    - "4200:4200"
    - "49152:49152"
